name       : python-simplebayes
version    : 1.5.8
release    : 3
source     :
    - https://pypi.python.org/packages/b9/73/764578df72934940d95a8941cbd374b56319562dda72630fc8bfeaefc350/simplebayes-1.5.8.tar.gz : 363418c0ef185ac2158ebbd6d8afb45aa997254fcb809a73ed20a7d5dccf8b85
license    : MIT
component  : programming.python
summary    : A memory-based, optional-persistence naïve bayesian text classifier
description: |
    A memory-based, optional-persistence naïve bayesian text classifier
builddeps  :
    - python-setuptools
setup      : |
    sed -e "s:long_description = open('README.rst', 'r').read(),::g" -i setup.py
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
